apiVersion: v1
kind: ConfigMap
metadata:
  name: mygraf-configmap-datasource
  labels:
    app: mygraf
data:
  datasources.yml: |-
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://192.168.99.105:30007
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mygraf-configmap-dash
  labels:
    app: mygraf
data:
  datasources.yml: |-
    apiVersion: 1
    providers:
      - name: 'a unique provider name'
        orgId: 1
        folder: ''
        folderUid: ''
        type: file
        disableDeletion: false
        editable: true
        updateIntervalSeconds: 10
        allowUiUpdates: true
        options:
          path: /var/lib/grafana/dashboards
          foldersFromFilesStructure: true
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: mygrafana
spec:
  selector:
    matchLabels:
      app: mygraf
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mygraf
    spec:
      containers:
      - image: vimal13/grafana
        name: mygraf
        ports:
        - containerPort: 9090
          name: mygraf
        volumeMounts:
        - name: mygraf-configmap-volume
          mountPath: /etc/grafana/provisioning/datasources/
        - name: mygraf-configmap-volume2
          mountPath: /etc/grafana/provisioning/dashboards/
      volumes:
      - name: mygraf-configmap-volume
        configMap:
          name: mygraf-configmap-datasource
      - name: mygraf-configmap-volume2
        configMap:
          name: mygraf-configmap-dash
---
apiVersion: v1
kind: Service
metadata:
  name: mygraf-service
spec:
  type: NodePort
  selector:
    app: mygraf
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30009