apiVersion: v1
kind: ConfigMap
metadata:
  name: myprom-configmap
  labels:
    app: myprom
data:
  prometheus.yml: |
    global:
     scrape_interval: 15s                      
     evaluation_interval: 15s 
    alerting:                                                                                                                 
      alertmanagers:                                                                                                          
        - static_configs:                                                                                                         
          - targets:                                                                                                                
            # - alertmanager:9093 
    scrape_configs:
      - job_name: 'prometheus'  
        static_configs:
        - targets: ['localhost:9090']

      - job_name: 'prometheus-job'
        static_configs:
        - targets: ['192.168.99.102:80']
---
apiVersion: v1
kind: Service
metadata:
  name: myprom-service
spec:
  type: NodePort
  selector:
    app: myprom
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 30007
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: myprometheus
spec:
  selector:
    matchLabels:
      app: myprom
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: myprom
    spec:
      containers:
      - image: vimal13/prometheus
        name: myprom
        ports:
        - containerPort: 9090
          name: myprom
        volumeMounts:
        - name: myprom-configmap-volume
          mountPath: /etc/prometheus/
      volumes:
      - name: myprom-configmap-volume
        configMap:
          name: myprom-configmap